#!/usr/bin/env -S uv run --quiet
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Validate the standalone Quark family generated by federation."""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOURCES_PATH = REPO_ROOT / ".github" / "scripts" / "sources.yml"
SKILLS_DIR = REPO_ROOT / "skills"
MARKETPLACE_PATH = REPO_ROOT / ".claude-plugin" / "marketplace.json"

EXPECTED_SKILLS = {
    "quark-env-preflight",
    "quark-install",
    "quark-onnx-autosearch-pro",
    "quark-onnx-debug",
    "quark-onnx-install",
    "quark-onnx-model-intake",
    "quark-onnx-ptq",
    "quark-onnx-result-validator",
    "quark-torch-debug",
    "quark-torch-export",
    "quark-torch-file2file-quantization",
    "quark-torch-install",
    "quark-torch-llm-eval",
    "quark-torch-llm-ptq-eval",
    "quark-torch-model-intake",
    "quark-torch-ptq",
    "quark-torch-result-validator",
}
LEGACY_NAMES = {
    "quark-doc-drift-check",
    "quark-onnx-export",
    "quark-quantization-result-validator",
    "quark-skill-sync",
    "quark-torch-eval-runner",
}
SKILL_NAME_RE = re.compile(r"`(quark-[a-z0-9-]+)`")
POINTER_TEXT = "Read and follow the instructions in `.claude/skills-impl/"


def fail(errors: list[str], message: str) -> None:
    errors.append(message)


def source_config(errors: list[str]) -> tuple[dict, dict[str, str]]:
    data = yaml.safe_load(SOURCES_PATH.read_text(encoding="utf-8"))
    matches = [
        source for source in data["sources"] if source.get("name") == "amd-quark"
    ]
    if len(matches) != 1:
        fail(errors, "sources.yml must contain exactly one `amd-quark` source.")
        return {}, {}
    source = matches[0]
    if source.get("repo", "").lower() != "amd/quark":
        fail(errors, "The Quark source repository must be amd/Quark.")
    if source.get("ref") != "v0.12":
        fail(errors, "The initial Quark federation must remain pinned to v0.12.")
    if source.get("resolve_wrappers") is not True:
        fail(errors, "The Quark source must enable strict wrapper resolution.")

    configured: dict[str, str] = {}
    for entry in source.get("skills", []):
        if not isinstance(entry, dict) or not entry.get("as") or not entry.get("name"):
            fail(errors, "Every Quark source skill must declare `name` and `as`.")
            continue
        configured[str(entry["as"])] = str(entry["name"])
    if set(configured) != EXPECTED_SKILLS:
        fail(
            errors,
            "Configured Quark skills differ from the 17 public release skills: "
            f"missing={sorted(EXPECTED_SKILLS - set(configured))}, "
            f"extra={sorted(set(configured) - EXPECTED_SKILLS)}",
        )
    return source, configured


def validate_skill(
    name: str,
    public_folder: str,
    expected_ref: str,
    errors: list[str],
) -> None:
    skill_dir = SKILLS_DIR / name
    skill_md = skill_dir / "SKILL.md"
    marker_path = skill_dir / ".federated.json"
    if not skill_md.is_file() or not marker_path.is_file():
        fail(errors, f"{name}: missing SKILL.md or .federated.json.")
        return

    text = skill_md.read_text(encoding="utf-8")
    if POINTER_TEXT in text:
        fail(errors, f"{name}: unresolved Quark wrapper pointer remains.")
    if "## Catalog portability" not in text:
        fail(errors, f"{name}: missing standalone catalog portability guidance.")

    marker = json.loads(marker_path.read_text(encoding="utf-8"))
    expected_public_path = f".claude/{public_folder}"
    if marker.get("path") != expected_public_path:
        fail(errors, f"{name}: marker path does not match {expected_public_path}.")
    if marker.get("ref") != expected_ref:
        fail(errors, f"{name}: marker ref does not match {expected_ref}.")
    if not re.fullmatch(r"[0-9a-f]{40}", str(marker.get("commit", ""))):
        fail(errors, f"{name}: marker is not pinned to a resolved commit SHA.")
    implementation = str(marker.get("implementation_path", ""))
    if not implementation.startswith(".claude/skills-impl/"):
        fail(errors, f"{name}: marker does not record its resolved implementation.")

    bundled = {path.stem for path in (skill_dir / "references").glob("quark-*.md")}
    all_markdown = "\n".join(
        path.read_text(encoding="utf-8") for path in skill_dir.rglob("*.md")
    )
    unresolved = set(SKILL_NAME_RE.findall(all_markdown)) - EXPECTED_SKILLS - bundled
    if unresolved:
        fail(errors, f"{name}: unresolved helper skill names: {sorted(unresolved)}")
    stale = {legacy for legacy in LEGACY_NAMES if legacy in all_markdown}
    if stale:
        fail(errors, f"{name}: stale upstream skill names remain: {sorted(stale)}")


def validate_behavioral_contracts(errors: list[str]) -> None:
    contracts = {
        "quark-torch-ptq": ("safetensors", "quark-onnx-ptq", "explicit"),
        "quark-onnx-ptq": (".onnx", "quark-torch-ptq", "approval"),
        "quark-onnx-autosearch-pro": ("AutoSearchPro", "n_trials", "approval"),
    }
    for name, required in contracts.items():
        text = (SKILLS_DIR / name / "SKILL.md").read_text(encoding="utf-8")
        missing = [phrase for phrase in required if phrase.lower() not in text.lower()]
        if missing:
            fail(errors, f"{name}: missing routing/safety contract terms {missing}.")

    for name, scripts in {
        "quark-torch-result-validator": {"quant_validation.py", "run_validation.py"},
        "quark-onnx-result-validator": {
            "quant_validation_onnx.py",
            "run_validation.py",
        },
    }.items():
        missing = [
            script for script in scripts if not (SKILLS_DIR / name / script).is_file()
        ]
        if missing:
            fail(errors, f"{name}: missing bundled validator scripts {missing}.")


def validate_marketplace(errors: list[str]) -> None:
    marketplace = json.loads(MARKETPLACE_PATH.read_text(encoding="utf-8"))
    published = {
        str(path).rstrip("/").split("/")[-1]
        for path in marketplace["plugins"][0]["skills"]
    }
    missing = EXPECTED_SKILLS - published
    if missing:
        fail(errors, f"Marketplace does not publish Quark skills: {sorted(missing)}")


def main() -> int:
    errors: list[str] = []
    source, configured = source_config(errors)
    for name, public_folder in sorted(configured.items()):
        validate_skill(name, public_folder, str(source.get("ref", "")), errors)
    validate_behavioral_contracts(errors)
    validate_marketplace(errors)

    if errors:
        for error in errors:
            print(f"[FAIL] {error}")
        print(f"Quark federation validation failed with {len(errors)} error(s).")
        return 1
    print(f"Quark federation validation passed for {len(EXPECTED_SKILLS)} skills.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
